### ISSUE TITLE
Pyhive problem

### ISSUE THREAD

**Issue by victor9496** [badbye/badbye.github.com#1]
Hi,

Sorry for being intrusive, I couldn't find a better way to send you a message.

I wonder if you solve the problem implementing udf in pyhive with the issue I find:
"https://github.com/dropbox/PyHive/issues/209"
, thank you!

**Comment by badbye** [comment]
Yes, I solved it after adding the UDF function in Hive correctly.  
There is nothing wrong with the PyHive package. Thank you for your attention.
